Balancing queues
asteny/rabbitmq-policymaker pull request #3
Opened 2020-03-02 12:31 UTC by asteny

2020-03-02 12:51 UTC, Pavkazzz commented on rabbitmq_policymaker/main.py
> +    help="Balancing master queues into policy groups",
Зачем аргумент? Чет не понял из хелпа

2020-03-02 12:51 UTC, Pavkazzz commented on rabbitmq_policymaker/main.py
> +        "Reasonable delta of queues between max and min numbers of queues"
"Разумная разница в очередях, между максимальным и минимальным количеством очередей на ноде, когда скрипт не делает ничего" - wut

2020-03-02 12:51 UTC, Pavkazzz commented on rabbitmq_policymaker/rabbitmq_policy.py
> +class QueuesOnNode:
Наверно просто Node

2020-03-02 12:51 UTC, Pavkazzz commented on rabbitmq_policymaker/rabbitmq_policy.py
> +            queue, vhost, min_queues_node = self.queues_for_relocate()
2 раза вызвал функцию просто так)

2020-03-02 12:51 UTC, Pavkazzz commented on rabbitmq_policymaker/rabbitmq_policy.py
> +                "priority": 999,
В аргументы?

2020-03-02 12:51 UTC, Pavkazzz commented on tests/test_rabbit.py
> +        return mock()
С тем же успехом можешь всегда 201 здесь отдавать без мока

2020-03-02 13:04 UTC, asteny commented on rabbitmq_policymaker/main.py
> +    help="Balancing master queues into policy groups",
балансировка мастер очередей это процесс переноса их с одного хоста на другой. это 2 кусок который нужно делать на кроликах. и к сожалению он только ручной. включил и по 1 очереди сидишь балансируешь. для этого и аргумент

2020-03-02 13:05 UTC, asteny commented on rabbitmq_policymaker/main.py
> +        "Reasonable delta of queues between max and min numbers of queues"
wut?

2020-03-02 13:16 UTC, asteny commented on rabbitmq_policymaker/rabbitmq_policy.py
> +class QueuesOnNode:
\+

2020-03-02 13:17 UTC, asteny commented on tests/test_rabbit.py
> +        return mock()
\+

2020-03-02 13:24 UTC, asteny commented on rabbitmq_policymaker/rabbitmq_policy.py
> +            queue, vhost, min_queues_node = self.queues_for_relocate()
\+

2020-03-03 07:12 UTC, lexsos commented on rabbitmq_policymaker/rabbitmq_policy.py
> +                sleep(self.wait_sleep)
Для чего тут задержки?

2020-03-03 07:43 UTC, asteny commented on rabbitmq_policymaker/rabbitmq_policy.py
> +                sleep(self.wait_sleep)
В принципе могу заменить слипы на вызов `is_queue_running `

2020-03-03 09:34 UTC, tzoiker commented on rabbitmq_policymaker/main.py
> +    help="Balancing master queues into policy groups",
Я всё равно не понял. Лучше попонятнее хелп

2020-03-03 09:36 UTC, tzoiker commented on rabbitmq_policymaker/main.py
> +        "Reasonable delta of queues between max and min numbers of queues"
Тоже не оч понял, что это значит. Reasonable не особо подходит для таких целей, оно или автоматически выбирает reasonable значение, либо ты руками задаёшь просто значение :)

2020-03-03 10:07 UTC, tzoiker requested changes

2020-03-03 10:07 UTC, tzoiker commented on rabbitmq_policymaker/main.py
> +        if len(queues_without_policy) > 0:
`if queues_without_policy:`

2020-03-03 10:07 UTC, tzoiker commented on rabbitmq_policymaker/rabbitmq_policy.py
>  class RabbitData:
Может `RabbitInfo` тогда? ВСё равно так называешь потом переменные

2020-03-03 10:07 UTC, tzoiker commented on rabbitmq_policymaker/rabbitmq_policy.py
>          self,
`self, *,`, если много аргументов порядковых, то порядок может ничего не говорить, поэтому стоит делать их именованными, чтобы потом случайно не перепутать

2020-03-03 10:07 UTC, tzoiker commented on rabbitmq_policymaker/rabbitmq_policy.py
>          dry_run: bool,
Я бы последним поставил и сделал по умолчанию `False`

2020-03-03 10:07 UTC, tzoiker commented on rabbitmq_policymaker/rabbitmq_policy.py
> +    def queues_for_relocate(self):
`queues_to_relocate`, а вообще непонятно почему так называется, учитывая, что возвращается только одна очередь. Ещё сделай `property`

2020-03-03 10:07 UTC, tzoiker commented on rabbitmq_policymaker/rabbitmq_policy.py
> +        queues_on_hosts = self.queues_on_hosts()
`queues_on_hosts` -> `get_queues_on_hosts` в итоге?

2020-03-03 10:07 UTC, tzoiker commented on rabbitmq_policymaker/rabbitmq_policy.py
> +            log.info(
`log.info("Max queues on %d. Min queues on %d", max_queues_node, min_queues_node)`

2020-03-03 10:07 UTC, tzoiker commented on rabbitmq_policymaker/rabbitmq_policy.py
> +        if queue_data:
Давай вложенность поменьше
```
if not queue_data:
    log.info("Nothing to balance")
    return

...
```

2020-03-03 10:07 UTC, tzoiker commented on rabbitmq_policymaker/rabbitmq_policy.py
> +            log.info(
```
log.info("Relocate queue %r. Policy body dict is %r", queue, dict_params)
```

2020-03-03 10:07 UTC, tzoiker commented on rabbitmq_policymaker/rabbitmq_policy.py
> +            if not self.dry_run:
```
if self.dry_run:
    log.info("It's dry run. Nothing changed")
    return
...
```

2020-03-03 10:07 UTC, tzoiker commented on rabbitmq_policymaker/rabbitmq_policy.py
> +                    policy_name="queue_master_balancer",
В константу вынеси `"queue_master_balancer"`

2020-03-03 11:01 UTC, asteny commented on rabbitmq_policymaker/rabbitmq_policy.py
> +                    policy_name="queue_master_balancer",
\+

2020-03-03 12:11 UTC, asteny commented on rabbitmq_policymaker/rabbitmq_policy.py
> +            if not self.dry_run:
\+

2020-03-03 12:11 UTC, asteny commented on rabbitmq_policymaker/rabbitmq_policy.py
> +            log.info(
\+

2020-03-03 12:12 UTC, asteny commented on rabbitmq_policymaker/rabbitmq_policy.py
> +        if queue_data:
\+

2020-03-03 12:12 UTC, asteny commented on rabbitmq_policymaker/rabbitmq_policy.py
> +            log.info(
\+

2020-03-03 12:12 UTC, asteny commented on rabbitmq_policymaker/rabbitmq_policy.py
> +    def queues_for_relocate(self):
\+

2020-03-03 12:19 UTC, asteny commented on rabbitmq_policymaker/main.py
> +        if len(queues_without_policy) > 0:
\+

2020-03-03 12:20 UTC, asteny commented on rabbitmq_policymaker/rabbitmq_policy.py
>  class RabbitData:
\+

2020-03-03 12:28 UTC, asteny commented on rabbitmq_policymaker/rabbitmq_policy.py
>          self,
\+

2020-03-03 12:33 UTC, asteny commented on rabbitmq_policymaker/rabbitmq_policy.py
>          dry_run: bool,
\+

2020-03-03 14:10 UTC, tzoiker requested changes

2020-03-03 14:10 UTC, tzoiker commented on rabbitmq_policymaker/main.py
> +            log.info("Nothing to do")
Давай тут тоже вложенность уменьшай

2020-03-03 14:10 UTC, tzoiker commented on rabbitmq_policymaker/rabbitmq_policy.py
>                      if er.status == 404:
Ипользуй `from http import HTTPStatus`

2020-03-03 14:10 UTC, tzoiker commented on rabbitmq_policymaker/rabbitmq_policy.py
> +    def get_queue_for_relocate(self):
`get_queue_for_relocate` -> `queue_to_relocate `

2020-03-03 19:54 UTC, mosquito commented on rabbitmq_policymaker/rabbitmq_policy.py
> +        bucket_number = bucket(f"{vhost}{queue}", len(self.policy_groups))
я вот не понимаю почему функция "ведро", возвращает "номер_ведра". `get_bucket` или `compute_bucket` ну или что-то такое.

2020-03-03 19:55 UTC, mosquito commented on rabbitmq_policymaker/rabbitmq_policy.py
> +            rabbit_nodes.append(f"rabbit@{node}")
раз переехал на docstrings классификатор в setup.py напиши что работаешь на питоне 3.6+

2020-03-03 20:01 UTC, mosquito requested changes

2020-03-03 20:01 UTC, mosquito commented on rabbitmq_policymaker/rabbitmq_policy.py
> +        return policy
если dry-run то policy никакой неть. Тут не нужен else а функция либо None должна возвращать, или падать.

2020-03-03 20:01 UTC, mosquito commented on rabbitmq_policymaker/rabbitmq_policy.py
> +        queues_on_host_list = []
кажется тут нужен генератор, и этот лист вообще не нужен.

2020-03-03 20:01 UTC, mosquito commented on rabbitmq_policymaker/rabbitmq_policy.py
> +                        Queue(vhost=queue_vhost, name=queue_name)
```python
yield node, Queue(vhost=queue_vhost, name=queue_name)

2020-03-03 20:01 UTC, mosquito commented on rabbitmq_policymaker/rabbitmq_policy.py
> +        queues_on_hosts = self.queues_on_hosts()
Иначе опять "ведро"

2020-03-03 20:01 UTC, mosquito commented on rabbitmq_policymaker/rabbitmq_policy.py
> +        return policy
тест бы на это...

2020-03-04 07:59 UTC, asteny commented on rabbitmq_policymaker/rabbitmq_policy.py
> +            rabbit_nodes.append(f"rabbit@{node}")
у меня датаклассы, а они с 3.7 поэтому в setup.py: python_requires=">=3.7"

2020-03-04 08:02 UTC, asteny commented on rabbitmq_policymaker/rabbitmq_policy.py
> +        bucket_number = bucket(f"{vhost}{queue}", len(self.policy_groups))
\+

2020-03-04 08:16 UTC, asteny commented on rabbitmq_policymaker/rabbitmq_policy.py
> +        return policy
Поправил, тест на создание полиси есть. Или ты про dry_run?

2020-03-04 08:19 UTC, dizballanze approved these changes

2020-03-04 08:47 UTC, asteny commented on rabbitmq_policymaker/rabbitmq_policy.py
> +        queues_on_host_list = []
мне нужен список сразу. я по нему выбираю нужные мне ноды по списку для полиси и ищу минимальные кол-ва очередей на нодах. генераторы не подойдут

2020-03-04 08:47 UTC, asteny commented on rabbitmq_policymaker/rabbitmq_policy.py
> +                        Queue(vhost=queue_vhost, name=queue_name)
мне нужен список сразу. я по нему выбираю нужные мне ноды по списку для полиси и ищу минимальные кол-ва очередей на нодах. генераторы не подойдут

2020-03-05 12:08 UTC, asteny commented on rabbitmq_policymaker/rabbitmq_policy.py
> +        return policy
добавил тест

2020-03-05 13:27 UTC, merged